### ISSUE TITLE
1.19同步后无法自启动

### ISSUE THREAD

**Issue by Guascoign** [Ivan-1F/MirrorSyncReforged#3]
`[MCDR] [13:39:49] [MSR/INFO] [mirror_sync_reforged]: copying ../MCDR_Survival/server\world -> ./server\world
Exception in thread MSR:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MCservers\MCDR_mirror\mcdreforged\api\decorator\new_thread.py", line 28, in wrapped_target
    raise e from None
  File "D:\MCservers\MCDR_mirror\mcdreforged\api\decorator\new_thread.py", line 25, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins\MirrorSyncReforged-v1.2.2.mcdr\mirror_sync_reforged\entry.py", line 164, in _sync
  File "plugins\MirrorSyncReforged-v1.2.2.mcdr\mirror_sync_reforged\entry.py", line 53, in copy_worlds
  File "C:\Program Files\Python310\lib\shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\Program Files\Python310\lib\shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('../MCDR_Survival/server\\world\\session.lock', './server\\world\\session.lock', '[Errno 13] Permission denied')]`
session.lock这个时间戳文件无法复制。
Windows server2019，1.19MCDR-fabric服务端

**Comment by Ivan-1F** [comment]
对 `session.lock` 文件操作的权限不足，尝试赋予其拷贝所需权限

**Comment by Guascoign** [comment]
session.lock这个文件是个时间戳文件，在生存服运行的时候游戏会打开这个文件无法复制。

https://minecraft.fandom.com/zh/wiki/Java%E7%89%88%E4%B8%96%E7%95%8C%E6%A0%BC%E5%BC%8F
此文件包含了该世界最后一次进入时的时间戳。该文件包含一个大端序的64位整数，为自1970-01-01 00:00:00（UTC）时区至今所经历的毫秒数。
与典型的lock文件不同，这一文件确保了最后访问这一世界的程序有读取和修改的权限。该过程通常如下所示：
1程序打开session.lock
2程序在session.lock写入当前时间戳
3程序对session.lock的变化进行监控
4如果session.lock内容发生变化，则程序中断并锁定世界。
即使在玩家开始这一世界之后Minecraft有时也会锁定这一世界。这通常会带来未知的后果。推荐在您需要获取修改世界的权限之前完全关闭Minecraft程序。

**Comment by Ivan-1F** [comment]
试试 [v1.3.0](https://github.com/Ivan-1F/MirrorSyncReforged/releases/tag/v1.3.0)
